drop table if exists users cascade;
drop table if exists request cascade;
drop table if exists items cascade;
drop table if exists bookings cascade;
drop table if exists comments cascade;

create table if not exists USERS (
user_id int not null generated by default as identity primary key,
user_name varchar(320) not null,
email varchar(320) UNIQUE not null
);

create table if not exists requests (
request_id int not null generated by default as identity primary key,
description varchar(320) not null,
created_date timestamp without time zone not null,
user_id int not null references users(user_id)
);

create table if not exists items (
item_id int not null generated by default as identity primary key,
name varchar(320) not null,
description varchar(320) not null,
available boolean not null,
user_id int not null references users(user_id),
request_id int references requests(request_id)
);

create table if not exists bookings (
booking_id int not null generated by default as identity primary key,
start_date timestamp without time zone not null,
end_date timestamp without time zone not null,
status varchar(8) not null,
user_id int not null references users(user_id),
item_id int references items(item_id)
);

create table if not exists comments (
comment_id int not null generated by default as identity primary key,
text varchar(320) not null,
created timestamp without time zone not null,
user_id int not null references users(user_id),
item_id int references items(item_id)
);


